---
title: "02-alpha-diversity"
author: "desantiago"
date: "2024-06-04"
output: github_document
---


```{r import.filter, include=FALSE}
source_rmd = function(file, skip_plots = TRUE) {
  temp = tempfile(fileext=".R")
  knitr::purl(file, output=temp)

  if(skip_plots) {
    old_dev = getOption('device')
    options(device = function(...) {
      .Call("R_GD_nullDevice", PACKAGE = "grDevices")
    })
  }
  source(temp)
  if(skip_plots) {
    options(device = old_dev)
  }
}

source_rmd(file = "01-filter-contamination-low-reads.Rmd")
# or sys.source("your-script.R", envir = knitr::knit_global())
```

## Plot Alpha Diversity (Observed ASVs)
Phyloseq uses ggplot to make publication ready figures 

```{r observed, out.width="100%"}
plot_richness(phylo_obj_tree_sans_contam_low_controls, x = "region", measures = c("Observed")) +
  geom_boxplot(aes(fill = habitat)) 
#  facet_wrap(habitat ~ ., scales = "free", drop = TRUE, ncol = 2, shrink = T) +
#  theme_bw() +
#  theme(axis.text.x = element_text(angle = 90))
```

## Plot Alpha Diversity (Shannon)
```{r shannon, out.width="100%"}
plot_richness(phylo_obj_tree_sans_contam_low_controls, x = "region", measures = c("Shannon")) +
  geom_boxplot(aes(fill = habitat)) 
#  facet_wrap(SampleType ~ ., scales = "free", drop = TRUE, ncol = 2, shrink = T) +
#  theme_bw() +
#  theme(axis.text.x = element_text(angle = 90))
```

## Plot Alpha Diversity (Simpson)
```{r simpson, out.width="100%"}
plot_richness(phylo_obj_tree_sans_contam_low_controls, x = "region", measures = c("Simpson")) +
  geom_boxplot(aes(fill = habitat))
#  facet_wrap(SampleType ~ ., scales = "free", drop = TRUE, ncol = 2, shrink = T) +
#  theme_bw() +
#  theme(axis.text.x = element_text(angle = 90))
```

